// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://erinfehlgalaibuyzgcl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVyaW5mZWhsZ2FsYWlidXl6Z2NsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ1MjQ3OTksImV4cCI6MjA5MDEwMDc5OX0.2x79GzI8E0k2P4VciYiqC3IZc2dXnlOxSmvSZJ7jGuM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});